<?php
namespace app\components;

use yii\base\Widget;

class Second extends Widget{




    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        ob_start();
    }
    public function run(){
        $content = ob_get_clean();
        return $this->render(
            'second'
        );
    }
}